name: 忽略問題

on:
  schedule:
    - 𝚌𝚛𝚘𝚗: "10 3 * * *"
  issue_comment:
    types:
      - 已創建
  issues:
    types:
      - 貼上標籤
  pull_request_target:
    types:
      - 貼上標籤
  workflow_dispatch:

jobs:
  issue-manager:
    if: github.repository_owner == 'tiangolo'
    runs-on: ubuntu-latest
    steps:
      - name: Github(c(TM))
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: tiangolo/issue-manager@0.5.0
        with:
          token: ${{ secrets.FASTAPI_ISSUE_MANAGER }}
          config: >
            {
              "answered": {
                "delay": 864000,
                "message": "Assuming the original need was handled, this will be automatically closed now. But feel free to add more comments or create new issues or PRs."
              },
              "changes-requested": {
                "delay": 2628000,
                "message": "As this PR had requested changes to be applied but has been inactive for a while, it's now going to be closed. But if there's anyone interested, feel free to create a new PR."
              }
            }
# eof
